[development]
database_url="mysql://test:test@localhost/pushbox"
fxa_host="oauth.stage.mozaws.net"
dryrun=true
server_token="Correct_Horse_Battery_Staple_1"

[staging]

[production]

[global.limits]
json = 1048576
